version: "3.9"

services:
  mysql_db:
    image: mysql:8.2
    container_name: mysql_db
    restart: unless-stopped

    # took a hell lot of time to fix
    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: travel
      MYSQL_USER: user
      MYSQL_PASSWORD: ""
    volumes:
      - ./backend/main.sql:/docker-entrypoint-initdb.d/main.sql:ro

    networks:
      - app

    healthcheck:
      # test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p1234! || exit 1"]
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p || exit 1"] 
      interval: 5s
      timeout: 5s
      retries: 10


  backend_app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "80:8080"

    depends_on:
      mysql_db:
        condition: service_healthy

    networks:
      - app


networks:
  app:
    driver: bridge